### ISSUE TITLE
'making' of undefined

### ISSUE THREAD

**Issue by pandaXiong01** [tnfe/shida#26]
/shida-main/server/router.js:58
  router.post("/quark/video/making", $middleware.auth, $controller.video.making);
                                                                         ^

[TypeError: Cannot read property 'making' of undefined
  at module.exports (/Users/xiongzhihua/Desktop/learn-project/shida-main/server/router.js:58:74)
  at initRouter (/Users/xiongzhihua/Desktop/learn-project/shida-main/server/core/loader.js:51:26)
  at new Application (/Users/xiongzhihua/Desktop/learn-project/shida-main/server/core/index.js:29:20)
  at Object.<anonymous> (/Users/xiongzhihua/Desktop/learn-project/shida-main/server/app.js:2:13)
  at Module._compile (internal/modules/cjs/loader.js:1085:14)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  at Module.load (internal/modules/cjs/loader.js:950:32)
  at Function.Module._load (internal/modules/cjs/loader.js:790:14)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
  at internal/main/run_main_module.js:17:47
]
[nodemon] app crashed - waiting for file changes before starting...

**Comment by drawcall** [comment]
https://github.com/tnfe/shida/blob/7226e03fd95f8a51c3bbca4df7ba81db1aa4565c/server/controller/video.js
